{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"downstream\"}",
     "legendFormat": "Download (mean)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"upstream\"}",
     "legendFormat": "Upload (mean)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "Ping (mean)" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "speedtest_bits_per_second{}", "legendFormat": "{{direction}}" }
   ]
  },
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"8.8.8.8\"} * 100.0 ",
     "legendFormat": "IP"
    },
    {
     "expr": "probe_success{instance=\"http://google.com\"} * 100.0 ",
     "legendFormat": "DNS"
    }
   ]
  },
  {
   "title": "Ping Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Ping RTT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "repeat": "host",
   "yaxes": [
    { "format": "s", "label": "RTT" }
   ],
   "targets": [
    {
     "expr": "sum(probe_dns_lookup_time_seconds{instance=\"8.8.8.8\"})",
     "legendFormat": "8.8.8.8"
    },
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"http://google.com\"})",
     "legendFormat": "google.com"
    },
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"http://github.com\"})",
     "legendFormat": "github.com"
    }
   ]
  }
 ]
}